# Generated by Django 4.1.4 on 2023-01-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_owner_alter_wishlist_wishlist_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('wishlist_user', 'listItem')},
        ),
    ]
